services:
  - type: web
    name: twokt-chating
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
